kind: Service
apiVersion: v1
metadata:
  name: jag-books-api-service
spec:
  ports:
    - port: 80
      targetPort: 8080
---
kind: Endpoints
apiVersion: v1
metadata:
  name: jag-books-api-service
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 8080
