apiVersion: apps/v1
kind: Deployment
metadata:
  name: jag-api-gateway-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      id: jag-api-gateway-pod-id
  template:
    metadata:
      labels:
        id: jag-api-gateway-pod-id
    spec:
      containers:
        - name: jag-api-gateway-pod-container1
          image: jag-api-gateway-img:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
