apiVersion: apps/v1
kind: Deployment
metadata:
  name: jag-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      label1: jag-api-gateway-pod-label1
  template:
    metadata:
      labels:
        label1: jag-api-gateway-pod-label1
    spec:
      containers:
        - name: jag-api-gateway-pod-container1
          image: jag-api-gateway-img:v1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
