apiVersion: v1
kind: Service
metadata:
  name: jag-api-gateway-svc
spec:
  type: NodePort
  selector:
    id: jag-api-gateway-pod-id
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
