apiVersion: apps/v1
kind: Deployment
metadata:
  name: jag-mongo-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      id: jag-mongo-db-pod-id
  template:
    metadata:
      labels:
        id: jag-mongo-db-pod-id
    spec:
      containers:
        - name: jag-mongo-db-pod-container1
          image: mongo
          ports:
            - containerPort: 27017
